[tool.poetry]
name = "jingwei"
version = "0.1.0"
description = "A reinforcement learning framwork."
authors = ["ZheyangXu <jishengxzy@hotmail.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
gymnasium = "^0.28.1"
torch = "^2.0.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
