[project]
name = "jingwei"
version = "0.1.0"
description = "a reinforcement learning framework."
authors = [
    {name = "ZheyangXu",email = "jishengxzy@hotmail.com"},
]
dependencies = [
    "numpy>=1.25.2",
    "gymnasium>=0.29.0",
    "torch>=2.0.1",
]
requires-python = ">=3.9"
readme = "README.md"
license = {text = "MIT"}

[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"
