[project]
name = "jingwei"
version = "0.1.0"
description = "又北二百里，曰发鸠之山，其上多柘木，有鸟焉，其状如乌，文首，白喙，赤足，名曰：“精卫”，其鸣自詨。是炎帝之少女，名曰女娃。女娃游于东海，溺而不返，故为精卫，常衔西山之木石，以堙于东海。漳水出焉，东流注于河。"
authors = [
    {name = "ZheyangXu", email = "jishengxzy@hotmail.com"},
]
dependencies = [
    "torch>=2.3.0",
    "gymnasium>=0.29.1",
    "numpy>=1.26.4",
]

requires-python = ">=3.11"
readme = "README.md"
license = {text = "MIT"}


[project.urls]
Homepage = "https://github.com/ZheyangXu/jingwei"
Repository = "https://github.com/ZheyangXu/jingwei"
Documentation = "https://github.com/ZheyangXu/jingwei-docs"


[project.optional-dependencies]
jax = [
    "jax>=0.4.28",
    "jaxlib>=0.4.28",
]
[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"


[tool.pdm]
distribution = true

[tool.black]
line-length = 100
target-version = ["py312"]

[tool.isort]
atomic = true
profile = "black"
src_paths = ["src", "tests"]
extra_standard_library = ["typing_extensions"]
indent = 4
lines_after_imports = 2
multi_line_output = 3
