from typing import Protocol

from jingwei.data.batch import Batch
from jingwei.infra.typing import TensorLike


class Agent(Protocol):

    def get_action(self, observation: TensorLike) -> TensorLike: ...

    def rtype(self) -> None: ...

    def is_on_policy(self) -> bool: ...

    def is_off_policy(self) -> bool: ...

    def is_offline(self) -> bool: ...

    def learn(self, batch: Batch) -> None: ...
