from typing import Protocol

import gymnasium as gym
from numpy.typing import DTypeLike, NDArray

from jingwei.infra.typing import (
    ActionType,
    DeviceType,
    Dtype,
    ObservationType,
    TensorLike,
)


class DataWrapperProtocol(Protocol):

    def observation_space(self) -> gym.Space: ...

    def action_space(self) -> gym.Space: ...

    def get_observation_shape(self) -> tuple[int, ...]: ...

    def get_action_shape(self) -> tuple[int, ...] | int: ...

    def device(self) -> DeviceType: ...

    def dtype(self) -> Dtype: ...

    def is_vec_env(self) -> bool: ...

    def num_vec_env(self) -> int: ...

    def unwrap_action(self, action: TensorLike) -> ActionType: ...

    def wrap_action(self, action: ActionType) -> TensorLike: ...

    def unwrap_observation(self, observation: TensorLike) -> ObservationType: ...

    def wrap_observation(self, observation: ObservationType) -> TensorLike: ...

    def to_numpy(self, tensor: TensorLike, dtype: DTypeLike) -> NDArray: ...

    def to_tensor(self, arr: NDArray, dtype: Dtype, device: DeviceType) -> TensorLike: ...
